parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Common:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Common/Domain/Entity/'
                prefix: 'App\Common\Domain\Entity\'
                alias: Common
            Contractors:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Contractors/Domain/Entity/'
                prefix: 'App\Contractors\Domain\Entity\'
                alias: Contractors
