framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    session: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    assets: ~